### ISSUE TITLE
DebugDrawer::update throws exception if there is no lines to draw [with solution].

### ISSUE THREAD

**Issue by pirogronian** [OGRECave/btogre#6]
If there is no lines to draw (in my case, no bodies in bullet world), DebugDrawer::update throws exception with message:

> what():  RuntimeAssertionException: mCurrentSection failed. You cannot call end() until after you call begin() in end at /build/ogre/src/ogre-13.1.1/OgreMain/src/OgreManualObject.cpp (line 324)

My solution: add a flag to mark if there were any line drawing:

`bool mBegan{false};`

and

```
void update()
{
	mWorld->debugDrawWorld();
	if (mBegan)
        {
            mLines.end();
            mBegan = false;
        }
}
```

and
```
void DebugDrawer::drawLine(const btVector3& from,const btVector3& to,const btVector3& color)
{
        mBegan = true;
```

**Comment by paroj** [comment]
should be fixed with aa9f662c9faff78a2465e476c128dfaea7f92281
